# Generated by Django 2.0.2 on 2019-06-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='ap',
            field=models.IntegerField(null=True),
        ),
    ]
