# Generated by Django 2.0.2 on 2019-07-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_status_ap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lossap', models.IntegerField(null=True)),
                ('dmg', models.IntegerField(null=True)),
                ('usemp', models.IntegerField(null=True)),
                ('behavior', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
