# Generated by Django 2.0.2 on 2019-07-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
