# Generated by Django 2.2.4 on 2019-09-12 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_status_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='food',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='happy',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='iritate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='medicine',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='refuresh',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='sleep',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='storess',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='tired',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='worry',
            field=models.IntegerField(null=True),
        ),
    ]
