# Generated by Django 2.2.4 on 2019-09-12 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_auto_20190912_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='storess',
            new_name='stress',
        ),
    ]
